#!/bin/sh
PATH=$PATH:/SMASH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib:/usr/local/lib:/lib/sfcb
export OPENSSL_CONF=/etc/ssl/openssl.cnf
export LD_LIBRARY_PATH

for i in /etc/init.d/*.sh; do
	if [ -r $i ]; then
	  . $i
	fi
done
unset i
proc_mgr&
